(function () {
    "use strict";
    angular.module('geoh.configs.module', [])
    /**
     * Config Constant
     *  SERVER_TEST_DEVICE: Temporary URL generated by Vagrant. Ej. terrible-parakeet-4069
     *  SERVER_TEST_LOCAL: Server URL.
     *  CURRENT_SERVER_TYPE: local | device.
     */
        .constant("Config", (function () {
            var API_VERSION = "v1";
            var SERVER_TEST_PRODUCTION = "http://api.parkiller-test.com/";
            var SERVER_TEST_LOCAL = "http://api.parkiller.app/";
            var CURRENT_SERVER_TYPE = "local";
            var url = ( CURRENT_SERVER_TYPE === 'local') ? SERVER_TEST_LOCAL.concat(API_VERSION) : SERVER_TEST_PRODUCTION.concat(API_VERSION);
            return {
                "SERVER_URL": url
            }
        })());
})();
